export interface Customer {
  id?: string; // Optional because ID is generated by Firestore
  name: string;
  address?: string;
  gst?: string;
  contact?: string;
}

export interface InvoiceItem {
  description: string;
  amount: number;
}

export interface Invoice {
  id?: string; // Optional because ID is generated by Firestore
  customer: string | Customer; // Could be customer ID or a populated customer object
  customerId?: string; // Store ID explicitly if customer is an object
  clientManager: string;
  items: InvoiceItem[];
  logo?: string;
  subtotal: number;
  gst: number;
  total: number;
  amountInWords: string;
  invoiceNumber?: string; // Usually generated or assigned
  date?: Date | string; // Or a Firestore Timestamp
}
