export interface Customer {
  id?: string; // Optional because ID is generated by Firestore
  name: string;
  email: string; // Added: Will be required and validated
  address?: string;
  gst?: string; // Existing, will add validation pattern
  phone?: string; // Added: Optional, will add validation pattern
  contact?: string; // Existing: General contact person/details, distinct from validated phone
}

export interface InvoiceItem {
  description: string;
  quantity: number;    // e.g., 2
  unitPrice: number;   // e.g., 50.00
  lineTotal: number;   // Calculated: quantity * unitPrice, e.g., 100.00
}

// Currency Definitions
export type CurrencyCode = 'USD' | 'INR' | 'EUR' | 'GBP'; // Add more as needed

export interface Currency {
  code: CurrencyCode;
  symbol: string;
  name: string;
}

export const SUPPORTED_CURRENCIES: Currency[] = [
  { code: 'INR', symbol: '₹', name: 'Indian Rupee' },
  { code: 'USD', symbol: '$', name: 'US Dollar' },
  { code: 'EUR', symbol: '€', name: 'Euro' },
  { code: 'GBP', symbol: '£', name: 'British Pound' }
];

export const DEFAULT_CURRENCY_CODE: CurrencyCode = 'INR';


// Define available template IDs
export type InvoiceTemplateId = 'classic' | 'modern' | 'simple';

export const DEFAULT_TEMPLATE_ID: InvoiceTemplateId = 'classic';

export interface InvoiceTemplate {
  id: InvoiceTemplateId;
  name: string; // User-friendly name for dropdown
}


export interface Invoice {
  id?: string; // Optional because ID is generated by Firestore
  customer: string | Customer; // Could be customer ID or a populated customer object
  customerId?: string; // Store ID explicitly if customer is an object
  clientManager: string;
  items: InvoiceItem[];
  logo?: string; // This might be deprecated if only default logo is used
  subtotal: number;
  gst: number;
  total: number;
  amountInWords: string;
  invoiceNumber?: string; // Usually generated or assigned
  date?: Date | string; // Or a Firestore Timestamp

  // Fields for Payment Tracking
  paymentStatus: 'Unpaid' | 'Partially Paid' | 'Paid' | 'Overdue';
  totalPaid: number;
  dueDate?: Date | string;

  // Template Selection
  templateId?: InvoiceTemplateId;
  currency: CurrencyCode; // Added: Currency for this invoice

  // Discount Fields
  discountType?: 'percentage' | 'fixed' | null; // Type of discount
  discountValue?: number | null; // Value of discount (percentage or fixed amount)
  discountAmount?: number; // Calculated discount amount, always stored
}

export interface Payment {
  id?: string; // Firestore generated ID
  invoiceId: string; // Foreign key to Invoice
  // currency?: CurrencyCode; // Optional: If payments can be in different currency than invoice
  paymentDate: Date; // Date of payment - Service layer should ensure this is a JS Date object
  amountPaid: number;
  paymentMethod?: 'Cash' | 'Credit Card' | 'Bank Transfer' | 'Cheque' | 'Other';
  notes?: string;
}

export interface Expense {
  id?: string; // Firestore generated ID
  date: Date | string; // Date of the expense - required
  category: string; // Expense category (e.g., Travel, Office Supplies) - required
  description: string; // Detailed description of the expense - required
  amount: number; // Amount of the expense - required, positive value
  currency: CurrencyCode; // Added: Currency for this expense
  vendor?: string; // Optional: Name of the vendor or place of purchase
  receiptUrl?: string; // Optional: URL to an uploaded receipt image/PDF
  // userId?: string; // Optional: If implementing multi-user system later
}

// Used for Product/Service Management Feature
export interface ProductOrService {
  id?: string; // Firestore generated
  name: string; // e.g., "Web Design Hourly Rate", "Standard Widget"
  description?: string; // Optional longer description
  defaultUnitPrice: number; // Standard price for one unit
  defaultUnit?: string; // Optional, e.g., "hour", "item", "kg"
}

// Used for Vendor Management Feature
export interface Vendor {
  id?: string; // Firestore generated
  name: string; // Required, e.g., "Office Supplies Co.", "Tech Solutions Ltd."
  contactPerson?: string;
  email?: string; // Optional, with email validation if provided
  phone?: string; // Optional, with phone pattern validation if provided
  address?: string;
  notes?: string; // General notes about the vendor
}

// Settings Page Models
export interface CompanyInformation {
  companyName?: string;
  address?: string;
  email?: string;
  phone?: string;
  gstOrTaxId?: string;
  // logoUrl is handled via assets, not here
}

export interface InvoicePrefixSetting {
  id: string; // Unique ID for this prefix configuration
  prefix: string; // e.g., "INV-", "QUOT-"
  nextInvoiceNumber: number;
}

export interface InvoiceSettings {
  defaultTemplateId?: InvoiceTemplateId;
  defaultPaymentTermsDays?: number; // e.g., 0 for Due on Receipt, 15 for Net 15
  invoicePrefixes: InvoicePrefixSetting[]; // Array to hold multiple prefix configurations
  defaultPrefixId?: string; // ID of the prefix to be used by default
  autoIncrementInvoiceNumber?: boolean; // Applies to the selected prefix for auto-generation
  defaultGstRate?: number; // Percentage, e.g., 18 for 18%
  defaultCurrencyCode?: CurrencyCode;
}

export interface PaymentSettings {
  acceptedPaymentMethodsDetails?: string; // Multi-line string for bank details, UPI, etc.
}

export interface UserProfileSettings {
  userName?: string; // Default client manager
  userEmail?: string; // For reference or future notification features
}

export interface AppSettings {
  id?: string; // Document ID in Firestore, e.g., 'user_default'
  companyInformation?: CompanyInformation;
  invoiceSettings?: InvoiceSettings;
  paymentSettings?: PaymentSettings;
  userProfileSettings?: UserProfileSettings;
}
